### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by danie1blackmore** [Azure/terraform-azurerm-lz-vending#424] opened 2024-10-11 07:33 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
Terraform v1.9.7
```

Please enter the module version that you are using:

```text
4.1.4
```

### Description
Changing the network `address_space` CIDR should re-configure the vnet peering if `hub_peering_enabled` is `true`. If you change the CIDR, for example from /24 to /21, the peering state becomes unsynchronized and needs to be recreated,

#### Steps to Reproduce

1. Set the `address_space` variable to ["10.0.0.0/24"]
2. Set the `hub_peering_enabled` to `true`
3. Deploy the resources and confirm the address space and peering status
4. Change `address_space` to ["10.0.0.0/21"] and deploy the resources
5. Open the vnet in Azure portal and selectpeerings. The peering will no longer be connected

Following this, the subscription should still be in the original management group
#### Additional context

Workaround: set the `hub_peering_enabled` option to `false` and redeploy. When the peering has gone, change the option back to `true` to re-establish peering

**Comment by matt-FFFFFF** [comment] 2024-10-11 09:06
Hi - this not a bug as it's not included in the module features, but is a dupe of #258

**Closed by matt-FFFFFF** 2024-10-11 09:06 UTC
