### ISSUE TITLE
bug: subscription providers shouldn't have dependencies on some of the other resources

### ISSUE THREAD

**Issue by sioakim** [Azure/terraform-azurerm-lz-vending#387] opened 2024-06-07 13:35 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Terraform 1.8.5
AzureRM lz-vending 4.1.2

Please paste the output of `terraform version` command from within the initialized directory:

```text
Terraform v1.8.5
on windows_amd64
```

Please enter the module version that you are using:

```text
registry.terraform.io/Azure/lz-vending/azurerm 4.1.2 
```

#### Steps to Reproduce

1. Use subscription_use_azapi     = true
2. Use virtual_network_enabled = true
3. Use subscription_register_resource_providers_enabled  = true
4. VNET fails to be created because the provider for Network is not registered

#### Screenshots
```
 Error: Failed to create/update resource
│ 
│   with module.sub_pe["sub-pe-prp-001"].module.virtualnetwork[0].azapi_resource.vnet["vnet1"],
│   on .terraform/modules/sub_pe/modules/virtualnetwork/main.tf line 37, in resource "azapi_resource" "vnet":
│   37: resource "azapi_resource" "vnet" {
│ 
│ creating/updating Resource: (ResourceId
│ "/subscriptions/xxxxxxx-5b3f-4c2c-b623-xxxxxxxxx/resourceGroups/rg-pe-prp-001/providers/Microsoft.Network/virtualNetworks/vnt-pe-prp-001"
│ / Api Version "2021-08-01"): PUT
│ https://management.azure.com/subscriptions/xxxxxxxx-5b3f-4c2c-b623-xxxxxxxxx/resourceGroups/rg-pe-prp-001/providers/Microsoft.Network/virtualNetworks/vnt-pe-prp-001
│ --------------------------------------------------------------------------------
│ RESPONSE 409: 409 Conflict
│ ERROR CODE: MissingSubscriptionRegistration
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "MissingSubscriptionRegistration",
│     "message": "The subscription is not registered to use namespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions.",
│     "details": [
│       {
│         "code": "MissingSubscriptionRegistration",
│         "target": "Microsoft.Network",
│         "message": "The subscription is not registered to use namespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions."
│       }
│     ]
│   }
│ }

```
#### Additional context

Workaround:
1. Create the subscription with virtual_network_enabled = false and then switch the flag to true and run it again - Tested and Works
2. Create a policy on MG level to register those providers (haven't tested)

More info:
Looking at the file: main.resourceproviders.tf

```
module "resourceproviders" {
  source            = "./modules/resourceprovider"
  for_each          = { for k, v in var.subscription_register_resource_providers_and_features : k => v if var.subscription_register_resource_providers_enabled }
  resource_provider = each.key
  features          = each.value
  subscription_id   = local.subscription_id

  depends_on = [
    module.resourcegroup,
    module.resourcegroup_networkwatcherrg,
    module.roleassignment,
    module.roleassignment_umi,
    module.subscription,
    module.usermanagedidentity,
    module.virtualnetwork,           // IS THIS NEEDED HERE????
  ]
}
```

I see there is a dependency on module.virtualnetwork.
There are other dependencies as well.
I don't see why the resource providers needs anything else other than the subscription.

**Comment by matt-FFFFFF** [comment] 2024-06-07 20:53
Hi!

The reason the RP has a dependency on all the other resources is this: during the process of registration the RP resources are not available.

What happens is that the AzAPI provider, via the go sdk, will register required providers as needed.

This 'just in time' registration only works if provider registration is enabled. If you have configured the provider to skip registration OR have the `ARM_SKIP_PROVIDER_REGISTRATION` set then this will fail.

When this issue has been reported before then the above has been the root cause.

**Comment by sioakim** [comment] 2024-06-07 21:06
As mentioned I have:
subscription_register_resource_providers_enabled = true

Why do I need a dependency on the virtual network or the resource group before I can launch the provider registration?

It should first register the Network provider and then create the VNET.
The code forces the VNET to be created before the Network Provider is registered. 

From my perspective the only dependency you need for the provider registration module is the existence of the subscription. 

As I said if I utilise the module with disabled vnet creation, the subscription and the providers are being created without issues. After that I enable the vnet and run the plan / apply and get everything in place.

Hope this clarifies the situation a bit more

**Comment by matt-FFFFFF** [comment] 2024-06-07 21:35
Hi,

I'm sorry I'm not talking about the module feature to register resource providers. I'm talking about the provider configuration, which can also be set via environment variable. This has been the root cause of this issue previously.

This module's RP registration should indeed be the final act, as it is an asynchronous operation and doing this first would mean all subsequent resource deployments would fail until the provider was fully registered. This process can take a number of minutes.

Please can you check that you have not got the `ARM_SKIP_PROVIDER_REGISTRATION` environment variable set, and that you have also not got a azapi provider block with RP registration disabled.

Ref: https://registry.terraform.io/providers/Azure/azapi/latest/docs#skip_provider_registration

Thank you

**Comment by matt-FFFFFF** [comment] 2024-06-07 21:40
Please see #314

**Comment by matt-FFFFFF** [comment] 2024-06-09 10:18
Closing as requested

**Closed** 2024-06-09 10:18 UTC
