### ISSUE TITLE
bug: Error cannot unmarshal string into Go

### ISSUE THREAD

**Issue by samuelchong** [Azure/terraform-azurerm-lz-vending#425] opened 2024-10-22 01:35 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

Please paste the output of `terraform version` command from within the initialized directory:

```text
$ terraform version
Terraform v1.9.8
on windows_amd64
+ provider registry.terraform.io/azure/azapi v2.0.1
+ provider registry.terraform.io/hashicorp/azuread v2.47.0
+ provider registry.terraform.io/hashicorp/azurerm v3.94.0
+ provider registry.terraform.io/hashicorp/random v3.6.3
+ provider registry.terraform.io/hashicorp/time v0.12.1
```

Please enter the module version that you are using:

```text
4.1.4
```

### Description
``` 
# output from terraform apply
│ Error: Invalid body
│ 
│   with module.landingzone.azapi_resource.telemetry_root,
│   on .terraform\modules\landingzone\main.telemetry.tf line 3, in resource "azapi_resource" "telemetry_root":
│    3: resource "azapi_resource" "telemetry_root" {
│
│ The argument "body" is invalid: unmarshaling failed: value:
│ "{\"properties\":{\"mode\":\"Incremental\",\"template\":{\"$schema\":\"https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#\",\"contentVersion\":\"1.0.0.0\",\"outputs\":{\"telemetry\":{\"type\":\"String\",\"value\":\"For
│ more information, see https://aka.ms/lz-vending/tf/telemetry\"}},\"parameters\":{},\"resources\":[],\"variables\":{}}}}", err: json: cannot unmarshal string into Go 
│ value of type map[string]interface {}
╵
╷
│ Error: Invalid Type
│
│   with module.landingzone.azapi_resource.telemetry_root,
│   on .terraform\modules\landingzone\main.telemetry.tf line 9, in resource "azapi_resource" "telemetry_root":
│    9:   body = jsonencode({
│   10:     properties = {
│   11:       mode     = "Incremental"
│   12:       template = local.telem_arm_subscription_template
│   13:     }
│   14:   })
│
│ The value must not be a string
╵
╷
│ Error: Invalid body
│
│   with module.landingzone.module.resourcegroup.azapi_resource.rg,
│   on .terraform\modules\landingzone\modules\resourcegroup\main.tf line 1, in resource "azapi_resource" "rg":
│    1: resource "azapi_resource" "rg" {
│
│ The argument "body" is invalid: unmarshaling failed: value: "{}", err: json: cannot unmarshal string into Go value of type map[string]interface {}
╵
╷
│ Error: Invalid body
│
│   with module.landingzone.module.resourcegroup_networkwatcherrg.azapi_resource.rg,
│   on .terraform\modules\landingzone\modules\resourcegroup\main.tf line 1, in resource "azapi_resource" "rg":
│    1: resource "azapi_resource" "rg" {
│
│ The argument "body" is invalid: unmarshaling failed: value: "{}", err: json: cannot unmarshal string into Go value of type map[string]interface {}
╵
╷
│ Error: Invalid Type
│
│   with module.landingzone.module.resourcegroup.azapi_resource.rg,
│   on .terraform\modules\landingzone\modules\resourcegroup\main.tf line 6, in resource "azapi_resource" "rg":
│    6:   body      = jsonencode({})
│
│ The value must not be a string
╵
╷
│ Error: Invalid Type
│
│   with module.landingzone.module.resourcegroup_networkwatcherrg.azapi_resource.rg,
│   on .terraform\modules\landingzone\modules\resourcegroup\main.tf line 6, in resource "azapi_resource" "rg":
│    6:   body      = jsonencode({})
│
│ The value must not be a string
╵
╷
│ Error: Invalid body
│
│   with module.landingzone.module.usermanagedidentity.azapi_resource.umi,
│   on .terraform\modules\landingzone\modules\usermanagedidentity\main.tf line 32, in resource "azapi_resource" "umi":
│   32: resource "azapi_resource" "umi" {
│
│ The argument "body" is invalid: unmarshaling failed: value: "{}", err: json: cannot unmarshal string into Go value of type map[string]interface {}
╵
╷
│ Error: Invalid Type
│
│   with module.landingzone.module.usermanagedidentity.azapi_resource.umi,
│   on .terraform\modules\landingzone\modules\usermanagedidentity\main.tf line 36, in resource "azapi_resource" "umi":
│   36:   body      = jsonencode({})
│
│ The value must not be a string
╵

```

#### Steps to Reproduce

1. terraforn init
2. terraform plan

#### Additional context
  source  = "Azure/lz-vending/azurerm"
It was working fine one on module 4.1.2 up until approx  a week ago. 

Start getting this error today.

**Comment by samuelchong** [comment] 2024-10-22 01:40
Tried disable_telemetry, still getting error  

"landingzone" {
  source  = "Azure/lz-vending/azurerm"
  version = "4.1.4"
  # version = "4.0.1"

  disable_telemetry = true

.......

sample variable files:
```
resource_groups = {
  "cicd" = {
    name     = "cicd"
    location = "australiaeast"
    tags     = { Workload = "abc" }
  },
  "sfa-base-rg" = {
    name     = "tss-xxx-base-ci-aue-rg"
    location = "australiaeast"
    tags     = { Workload = "abc" }
  },

```

**Comment by samuelchong** [comment] 2024-10-22 02:43
looks like an issue with jsonencode({})

**Comment by samuelchong** [comment] 2024-10-22 07:54
I haven't found any workaround.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by matt-FFFFFF** [comment] 2024-10-22 08:41
As a workaround please cap your AzAPI provider version to ~> 1.15

We will work on supporting AzAPI v2 in the coming weeks

**Comment by matt-FFFFFF** [comment] 2024-10-22 16:08
Closing as dupe of #406

**Closed** 2024-10-22 16:08 UTC
Labels: Needs: Author Feedback :pencil2:
