### ISSUE TITLE
bug: When routing intent is enabled in the module subsequent runs attempt to remove the route table association and propagation

### ISSUE THREAD

**Issue by laingsc** [Azure/terraform-azurerm-lz-vending#289] opened 2023-11-28 01:38 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

Please paste the output of `terraform version` command from within the initialized directory:

```text
1.6.3
```

Please enter the module version that you are using:

```text
3.4.1
```

### Description

When routing intent is enabled in the module subsequent runs it attempts to remove the route table association and propagation.  Azure automatically creates the route table association and route propagation when routing intent is enabled on the virtual hub.

#### Steps to Reproduce

Here's the vnet part of the code here, I've renamed a few things because this is public:

```
# virtual networks
  virtual_network_enabled = true
  virtual_networks = {
    vnet = {
      name                        = "my-vnet"
      address_space               = ["10.158.0.0/23"]
      resource_group_name         = "my-rg"
      resource_group_lock_enabled = false
      dns_servers                 = [data.tfe_outputs.connectivity.values.azure_firewall_private_ip]

      vwan_connection_enabled                  = true
      vwan_connection_name                     = "my-network-vnet-connection"
      vwan_hub_resource_id                     = data.tfe_outputs.connectivity.values.hub_resource_id
      vwan_security_configuration = {
        routing_intent_enabled = true
      }

      tags = local.tags_my_tags
    }
  }
```
It creates it perfectly fine, but since Azure manages the associate route tables and route table resource ids, this module attempts to remove that.

If I add in these two bits it doesn't make a difference:
```
      vwan_associated_routetable_resource_id   = data.tfe_outputs.connectivity.values.default_route_id
      vwan_propagated_routetables_resource_ids = [data.tfe_outputs.connectivity.values.none_route_id]
```

I'm thinking ignore changes for vwan_associated_routetable_resource_id   &  vwan_propagated_routetables_resource_ids if routing_intent_enabled is true might work...dynamic block type thing.

#### Screenshots

```
 # module.lz_vending_location_information_non_production.module.virtualnetwork[0].azapi_resource.vhubconnection["vnet"] will be updated in-place
  ~ resource "azapi_resource" "vhubconnection" {
      ~ body                      = jsonencode(
          ~ {
              ~ properties = {
                  ~ routingConfiguration   = {
                      - associatedRouteTable  = {
                          - id = "**************************/hubRouteTables/defaultRouteTable"
                        }
                      - propagatedRouteTables = {
                          - ids    = [
                              - {
                                  - id = "************************/hubRouteTables/noneRouteTable"
                                },
                            ]
                          - labels = [
                              - "none",
                            ]
                        }
                      - vnetRoutes            = {
                          - staticRoutes       = []
                          - staticRoutesConfig = {
                              - propagateStaticRoutes          = true
                              - vnetLocalRouteOverrideCriteria = "Contains"
                            }
                        }
                    } -> null
                    # (2 unchanged attributes hidden)
                }
            }
        )
```

#### Additional context

Otherwise it's a great module, to spin up ALZ's quickly....I like how it doesn't try and do everything....because we should be doing the rest in it's own workspace...

**Comment by matt-FFFFFF** [comment] 2023-11-28 10:16
Thanks! we will look into this:

https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_resource#ignore_body_changes

This could help here.

**Comment by matt-FFFFFF** [comment] 2023-11-28 12:13
The issue is here:

https://github.com/Azure/terraform-azurerm-lz-vending/blob/f5d2209403f36186bbec6f0f3f56d26c15a06236/modules/virtualnetwork/main.tf#L170

**Comment by laingsc** [comment] 2023-11-28 23:09
Ah yes, didn't look into the module at all, but assumed it was something like that!  

Not used the azapi resource much at all, but that's good it's got an ignore_missing equivalent!

**Comment by hlokensgard** [comment] 2024-01-03 12:38
@matt-FFFFFF any update for this bug? We are having the same issue.

**Comment by matt-FFFFFF** [comment] 2024-01-29 16:12
Hi! Working on this now. Testing is going well and we will release this fix in 4.0.1

**Comment by matt-FFFFFF** [comment] 2024-01-29 16:16
For those interested I have added this to the vhub connection resource:

```terraform
ignore_body_changes = each.value.vwan_security_configuration.routing_intent_enabled ? ["properties.routingConfiguration"] : []
```

**Comment by matt-FFFFFF** [comment] 2024-02-02 13:39
Still trying to fix this

The testing is fun and takes a long time. Now moving to using `merge()` for the body.

```terraform
  body = jsonencode({
    properties = merge({
      enableInternetSecurity = each.value.vwan_security_configuration.secure_internet_traffic
      remoteVirtualNetwork = {
        id = local.virtual_network_resource_ids[each.key]
      }
      },
      # Only supply routingConfiguration if routing_intent_enabled is set to false
      each.value.vwan_security_configuration.routing_intent_enabled ? {} : {
        routingConfiguration = {
          associatedRouteTable = {
            id = each.value.vwan_associated_routetable_resource_id != "" ? each.value.vwan_associated_routetable_resource_id : "${each.value.vwan_hub_resource_id}/hubRouteTables/defaultRouteTable"
          }
          propagatedRouteTables = {
            ids    = each.value.vwan_security_configuration.secure_private_traffic ? local.vwan_propagated_noneroutetables_resource_ids[each.key] : local.vwan_propagated_routetables_resource_ids[each.key]
            labels = each.value.vwan_security_configuration.secure_private_traffic ? ["none"] : local.vwan_propagated_routetables_labels[each.key]
          }
        }
    })
  })
  ignore_body_changes = each.value.vwan_security_configuration.routing_intent_enabled ? ["properties.routingConfiguration"] : []
```

**Closed** 2024-02-03 14:02 UTC
Labels: bug :bug:, PR: Referenced :eyes:

**Comment by laingsc** [comment] 2024-02-04 21:14
Nice one folks, thank-you, will upgrade today and see if there's any breaking changes, should be sweet though!
